### ISSUE TITLE
SyntaxError: Non-UTF-8 code starting with '\x8d'.......  ✔️ Execution completed! 

### ISSUE THREAD

**Issue by AnkitShakya95** [AshutoshGoswami24/text-leech-bot#7]
Running command: python3 modules/main.py ... SyntaxError: Non-UTF-8 code starting with '\x8d' in file /content/repo/text-leech-bot2/modules/main.py on line 5, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details ✔️ Execution completed! 
![Screenshot_2024_1021_143958](https://github.com/user-attachments/assets/9272051c-9700-480b-94b6-f108a2892a04)

**Comment by AshutoshGoswami24** [comment]
Oh, wait! Is it on Google Colab? If you try to do it on a VPS, then use Docker. For more help, come to our support group: [Ashu Support 😁](https://t.me/AshuSupport.)
